#line 2 "Parser/ansicLex.c"

#line 4 "Parser/ansicLex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[283] =
    {   0,
        0,    0,  100,   98,   97,   97,   85,   98,   91,   84,
       98,   79,   80,   89,   88,   76,   87,   83,   90,   40,
       41,   77,   73,   92,   78,   93,   96,   38,   38,   81,
       82,   94,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   74,   95,   75,
       86,   72,    0,    0,   49,    0,   58,   67,   59,    0,
        0,   56,   64,   54,   65,   55,   66,    0,   44,    1,
        2,   57,   45,   40,    0,    0,   40,    0,   41,   41,
       63,   69,   71,   70,   62,   38,    0,    0,   60,   38,
       38,   38,   38,   38,   38,   38,   11,   38,   38,   38,

       38,   38,   38,   38,   19,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   61,   68,   49,
        0,   42,   51,    0,   44,    2,   44,    0,   45,    0,
       43,    0,   39,   53,   52,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   17,   38,
       20,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,    0,   44,    0,
       44,    0,   45,   43,   47,   48,   39,   39,    3,    4,
       38,    6,    7,   38,   38,   38,   38,   13,   14,   38,
       38,   38,   18,   21,   38,   38,   38,   38,   38,   38,

       38,   38,   36,   38,   38,   38,   33,   38,   38,    0,
       44,   47,   47,   47,   47,   48,    0,   39,   39,    5,
        8,   38,   38,   38,   38,   37,   16,   38,   38,   24,
       38,   38,   38,   38,   38,   38,   31,   38,   38,   35,
        0,   47,   47,   47,   47,    0,   47,   47,   46,   39,
       38,   38,   12,   15,   38,   23,   25,   26,   27,   28,
       29,   38,   38,   38,   47,    0,   47,   47,   48,   46,
       38,   10,   38,   30,   38,   38,   47,    9,   22,   32,
       34,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   29,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   48,   49,
       50,   51,   29,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    6,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[294] =
    {   0,
        0,    0,  529,  530,  530,  530,  505,   62,  504,   59,
      492,  530,  530,  502,   56,  530,   57,   55,   67,   82,
      126,  530,  530,   53,  495,   61,  530,    0,   81,  530,
      530,  482,  449,   41,   58,   53,   57,   70,  445,   56,
      444,  452,   74,   73,  443,  435,  440,  530,   54,  530,
      530,  530,  121,   87,  530,  480,  530,  530,  530,  102,
      474,  530,  530,  530,  530,  530,  530,  466,  133,  530,
        0,  530,  159,   90,  175,  152,  152,  465,    0,  165,
      455,  530,  530,  530,  451,    0,  200,  439,  530,  418,
      421,  429,  416,  428,  415,  420,  404,  405,  402,  402,

      402,  398,  395,  392,    0,  391,  395,   84,  392,   87,
       97,  393,  382,  385,  101,   88,  390,  530,  530,  530,
      431,  530,  530,  196,  530,    0,  200,  219,  530,  204,
      226,    0,  231,  530,  530,  383,  382,  391,  385,  371,
       34,  385,  383,  379,  365,  371,  358,  373,    0,  359,
        0,  365,  361,  347,  349,  351,  358,  344,  342,  339,
      351,  349,  337,  341,  345,  346,  335,  207,  246,  263,
      530,  231,  266,  530,  138,  297,  333,  240,    0,    0,
      335,    0,    0,  324,  332,  321,  322,    0,    0,  316,
      321,  304,    0,    0,  304,  301,  292,  302,  292,  296,

      301,  293,    0,  290,  280,  285,    0,  266,  278,  234,
      337,  377,  530,  262,  413,  530,    0,  319,  112,    0,
        0,  263,  264,  269,  257,    0,    0,  245,  249,    0,
      257,  249,  240,  212,  216,  218,    0,  191,  194,    0,
        0,  197,    0,  449,  530,    0,  243,    0,  260,  271,
      180,  178,    0,    0,  188,    0,    0,    0,    0,    0,
        0,  162,  157,  150,  270,    0,  255,    0,  274,  530,
      150,    0,  136,    0,  144,  131,  275,    0,    0,    0,
        0,  530,  496,  502,  504,  510,  516,  519,  157,  153,
      134,  106,   64

    } ;

static const flex_int16_t yy_def[294] =
    {   0,
      282,    1,  282,  282,  282,  282,  282,  283,  282,  282,
      284,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  285,  285,  282,
      282,  282,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  282,  282,  282,
      282,  282,  283,  286,  282,  283,  282,  282,  282,  284,
      284,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      287,  282,  282,   20,  282,  282,  282,  288,   21,  282,
      282,  282,  282,  282,  282,  285,  283,  284,  282,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  282,  282,  282,
      286,  282,  282,  282,  282,  287,  282,  282,  282,  282,
      282,  289,  288,  282,  282,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  282,  282,  282,
      282,  282,  282,  282,  289,  282,  282,  282,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  282,
      282,  282,  282,  176,  282,  282,  290,  177,  177,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      291,  212,  212,  282,  282,  292,  215,  244,  290,  282,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  291,  293,  244,  244,  292,  282,
      285,  285,  285,  285,  285,  285,  293,  285,  285,  285,
      285,    0,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282

    } ;

static const flex_int16_t yy_nxt[595] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   28,   29,
       28,   28,   30,    4,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   28,   40,   28,   41,   28,   28,   28,
       28,   42,   43,   44,   45,   46,   47,   28,   28,   28,
       48,   49,   50,   51,   54,   58,   55,   63,  277,   68,
       65,   69,   69,   69,   81,   82,  118,   70,   64,   66,
       67,   59,   71,   84,   85,   87,  184,  185,   88,   72,
       91,  120,   92,   96,   93,   56,   73,  105,   74,   74,

       75,   94,   97,   98,  106,   99,  101,   95,   76,  122,
      269,   77,   77,   78,  100,  119,  102,  109,  110,  103,
      121,  282,   76,   54,  113,   55,  153,  111,   77,  156,
      112,  114,  165,  158,  166,   61,   77,  154,  265,   78,
       73,  250,   79,   79,   79,  163,  157,  282,  159,   69,
       69,   69,   76,  164,   56,   80,   80,  249,  250,  124,
      125,  175,  125,  130,  212,  130,   76,  213,  131,  131,
      131,  281,   80,  124,  125,  127,  127,  127,  212,  125,
       80,   77,   77,  280,  213,  128,  129,  279,  129,   73,
      278,   75,   75,   75,   80,   80,  276,  275,   77,  128,

      129,   76,   54,  274,   55,  129,   77,  168,  282,  168,
      282,   80,  169,  169,  169,   76,  127,  127,  127,   80,
      131,  131,  131,  169,  169,  169,  170,  171,  273,  171,
      172,  272,  172,   56,  271,  173,  173,  173,  264,  263,
      170,  171,  131,  131,  131,  176,  171,  173,  173,  173,
      211,  211,  211,  174,  282,  174,  282,  177,  262,  261,
      178,  178,  169,  169,  169,  260,  282,  174,  282,  178,
      178,  177,  174,  125,  210,  125,  210,  178,  259,  211,
      211,  211,  173,  173,  173,  178,  178,  125,  244,  270,
      258,  245,  125,  129,  178,  129,  257,  256,  255,  213,

      178,  178,  244,  216,  245,  254,  270,  129,  245,  253,
      252,  251,  129,  214,  214,  214,  213,  178,  240,  239,
      216,  245,  214,  215,  214,  178,  216,  238,  237,  236,
      282,  235,  282,  214,  214,  214,  214,  215,  214,  234,
      233,  232,  231,  216,  217,  230,  217,  176,  250,  218,
      218,  218,  229,  211,  211,  211,  228,  227,  218,  219,
      218,  226,  178,  178,  171,  250,  171,  225,  224,  218,
      218,  218,  218,  219,  218,  223,  222,  221,  171,  178,
      220,  209,  208,  171,  207,  206,  205,  178,  241,  204,
      241,  203,  202,  242,  242,  242,  201,  200,  199,  198,

      197,  196,  242,  243,  242,  195,  213,  194,  193,  192,
      191,  190,  189,  242,  242,  242,  242,  243,  242,  188,
      187,  186,  183,  213,  246,  182,  246,  181,  180,  247,
      247,  247,  179,  282,  167,  162,  161,  160,  247,  248,
      247,  155,  245,  152,  151,  150,  149,  148,  147,  247,
      247,  247,  247,  248,  247,  146,  145,  144,  143,  245,
      266,  142,  266,  141,  140,  267,  267,  267,  139,  138,
      137,  136,   61,  135,  267,  268,  267,  134,  245,  132,
      123,   60,  282,  117,  116,  267,  267,  267,  267,  268,
      267,  115,  108,  107,  104,  245,   53,   53,   53,   53,

       53,   53,   60,   90,   89,   60,   60,   60,   86,   86,
       54,   54,   54,   54,   54,   54,  126,   83,  126,  126,
      126,  126,  133,  133,   62,   61,   57,   52,  282,    3,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282

    } ;

static const flex_int16_t yy_chk[595] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   10,    8,   15,  293,   18,
       17,   18,   18,   18,   24,   24,   49,   19,   15,   17,
       17,   10,   19,   26,   26,   29,  141,  141,   29,   19,
       34,   54,   34,   36,   35,    8,   20,   40,   20,   20,

       20,   35,   36,   37,   40,   37,   38,   35,   20,   60,
      292,   20,   20,   20,   37,   49,   38,   43,   43,   38,
       54,   74,   20,   53,   44,   53,  108,   43,   20,  110,
       43,   44,  116,  111,  116,   60,   20,  108,  291,   20,
       21,  219,   21,   21,   21,  115,  110,   74,  111,   69,
       69,   69,   21,  115,   53,   21,   21,  290,  219,   69,
       69,  289,   69,   76,  175,   76,   21,  175,   76,   76,
       76,  276,   21,   69,   69,   73,   73,   73,  175,   69,
       21,   77,   77,  275,  175,   73,   73,  273,   73,   75,
      271,   75,   75,   75,   80,   80,  264,  263,   77,   73,

       73,   75,   87,  262,   87,   73,   77,  124,  242,  124,
      242,   80,  124,  124,  124,   75,  127,  127,  127,   80,
      130,  130,  130,  168,  168,  168,  127,  127,  255,  127,
      128,  252,  128,   87,  251,  128,  128,  128,  239,  238,
      127,  127,  131,  131,  131,  133,  127,  172,  172,  172,
      210,  210,  210,  131,  247,  131,  247,  133,  236,  235,
      133,  133,  169,  169,  169,  234,  267,  131,  267,  178,
      178,  133,  131,  169,  170,  169,  170,  133,  233,  170,
      170,  170,  173,  173,  173,  133,  178,  169,  214,  249,
      232,  214,  169,  173,  178,  173,  231,  229,  228,  265,

      250,  250,  214,  269,  277,  225,  249,  173,  214,  224,
      223,  222,  173,  176,  176,  176,  265,  250,  209,  208,
      269,  277,  176,  176,  176,  250,  176,  206,  205,  204,
      218,  202,  218,  176,  176,  176,  176,  176,  176,  201,
      200,  199,  198,  176,  177,  197,  177,  177,  218,  177,
      177,  177,  196,  211,  211,  211,  195,  192,  177,  177,
      177,  191,  177,  177,  211,  218,  211,  190,  187,  177,
      177,  177,  177,  177,  177,  186,  185,  184,  211,  177,
      181,  167,  166,  211,  165,  164,  163,  177,  212,  162,
      212,  161,  160,  212,  212,  212,  159,  158,  157,  156,

      155,  154,  212,  212,  212,  153,  212,  152,  150,  148,
      147,  146,  145,  212,  212,  212,  212,  212,  212,  144,
      143,  142,  140,  212,  215,  139,  215,  138,  137,  215,
      215,  215,  136,  121,  117,  114,  113,  112,  215,  215,
      215,  109,  215,  107,  106,  104,  103,  102,  101,  215,
      215,  215,  215,  215,  215,  100,   99,   98,   97,  215,
      244,   96,  244,   95,   94,  244,  244,  244,   93,   92,
       91,   90,   88,   85,  244,  244,  244,   81,  244,   78,
       68,   61,   56,   47,   46,  244,  244,  244,  244,  244,
      244,   45,   42,   41,   39,  244,  283,  283,  283,  283,

      283,  283,  284,   33,   32,  284,  284,  284,  285,  285,
      286,  286,  286,  286,  286,  286,  287,   25,  287,  287,
      287,  287,  288,  288,   14,   11,    9,    7,    3,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Parser/ansicLex.l"
#line 2 "Parser/ansicLex.l"
#include "../Tree/tree.h"
#include "ansicParser.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void count();
void comment();
// int typeCheck();

int column = 0;
#line 713 "Parser/ansicLex.c"
#line 714 "Parser/ansicLex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 25 "Parser/ansicLex.l"


#line 934 "Parser/ansicLex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 283 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 530 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "Parser/ansicLex.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "Parser/ansicLex.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_AUTO,yylineno);			return(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_BOOL,yylineno); 		return(BOOL);	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_BREAK,yylineno);		return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CASE,yylineno);			return(CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CHAR,yylineno);			return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONST,yylineno);		return(CONST); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONTINUE,yylineno);		return(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_DEFAULT,yylineno);		return(DEFAULT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_DO,yylineno);			return(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_DOUBLE,yylineno);		return(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ELSE,yylineno);			return(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ENUM,yylineno);			return(ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_EXTERN,yylineno);		return(EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_FLOAT,yylineno);		return(FLOAT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_FOR,yylineno);			return(FOR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_GOTO,yylineno);			return(GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_IF,yylineno);			return(IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_INT,yylineno);			return(INT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_LONG,yylineno);			return(LONG); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_REGISTER,yylineno);		return(REGISTER); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_RETURN,yylineno);		return(RETURN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_LONG,yylineno);      	return(SHORT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_SIGNED,yylineno);		return(SIGNED); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_SIZEOF,yylineno);		return(SIZEOF); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_STATIC,yylineno);		return(STATIC); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_STRUCT,yylineno);		return(STRUCT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_SWITCH,yylineno);		return(SWITCH); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_TYPEDEF,yylineno);		return(TYPEDEF); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_UNION,yylineno);		return(UNION); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_UNSIGNED,yylineno);		return(UNSIGNED); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_VOID,yylineno);			return(VOID); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_VOLATILE,yylineno);		return(VOLATILE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_WHILE,yylineno);		return(WHILE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_TRUE,yylineno);			return(TRUE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_FALSE,yylineno);		return(FALSE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_IDENTIFIER,yylineno);	return(IDENTIFIER); /*IDENTIFIER*/ }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 68 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_INT,yylineno);	return(CONSTANT_INT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 69 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_INT,yylineno);	return(CONSTANT_INT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 70 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_INT,yylineno);	return(CONSTANT_INT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 71 "Parser/ansicLex.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 73 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_DOUBLE,yylineno);	return(CONSTANT_DOUBLE); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 74 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_DOUBLE,yylineno);	return(CONSTANT_DOUBLE); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 75 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_DOUBLE,yylineno);	return(CONSTANT_DOUBLE); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 76 "Parser/ansicLex.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 77 "Parser/ansicLex.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 78 "Parser/ansicLex.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 79 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_STRING_LITERAL,yylineno);	return(STRING_LITERAL); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 80 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_STRING_LITERAL,yylineno);	return(STRING_LITERAL); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 82 "Parser/ansicLex.l"
{ count(); return(ELLIPSIS); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_RIGHT_,yylineno);	return(RIGHT_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 84 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_LEFT,yylineno);		return(LEFT_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 85 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_ADD,yylineno);		return(ADD_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 86 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_SUB,yylineno);		return(SUB_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_MUL,yylineno);		return(MUL_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 88 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_DIV,yylineno);		return(DIV_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 89 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_MOD,yylineno);		return(MOD_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 90 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_AND,yylineno);		return(AND_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 91 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_XOR,yylineno);		return(XOR_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 92 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_OR,yylineno);		return(OR_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 93 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_RIGHT,yylineno);			return(RIGHT_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 94 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_LEFT,yylineno);			return(LEFT_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 95 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_INC,yylineno);			return(INC_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 96 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_DEC,yylineno);			return(DEC_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 97 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_PTR,yylineno);			return(PTR_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_AND,yylineno);			return(AND_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 99 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_OR,yylineno);			return(OR_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 100 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_LE,yylineno);			return(LE_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 101 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_GE,yylineno);			return(GE_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 102 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_EQ,yylineno);			return(EQ_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 103 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_NE,yylineno);			return(NE_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 104 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(';',yylineno);return(';'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 105 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('{',yylineno);return('{'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 106 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('}',yylineno);return('}'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 107 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(',',yylineno);return(','); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 108 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(':',yylineno);return(':'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 109 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('=',yylineno);return('='); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 110 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('(',yylineno);return('('); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 111 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(')',yylineno);return(')'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 112 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('[',yylineno);return('['); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 113 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(']',yylineno);return(']'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 114 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('.',yylineno);return('.'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 115 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('&',yylineno);return('&'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 116 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('!',yylineno);return('!'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 117 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('~',yylineno);return('~'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 118 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('-',yylineno);return('-'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 119 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('+',yylineno);return('+'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 120 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('*',yylineno);return('*'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 121 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('/',yylineno);return('/'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 122 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('%',yylineno);return('%'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 123 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('<',yylineno);return('<'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 124 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('>',yylineno);return('>'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 125 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('^',yylineno);return('^'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 126 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('|',yylineno);return('|'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 127 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('?',yylineno);return('?'); }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 129 "Parser/ansicLex.l"
{ count(); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 130 "Parser/ansicLex.l"
{ }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 132 "Parser/ansicLex.l"
ECHO;
	YY_BREAK
#line 1498 "Parser/ansicLex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 283 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 283 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 282);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 132 "Parser/ansicLex.l"


int yywrap()
{
	return 1;
}

void comment()
{
	column = 0;
	char c, prev = 0;
	
	while ((c = getchar()) != EOF)      
	{
		if (c == '/' && prev == '*')
			return;
		prev = c;
	}
	printf("unterminated comment");
}

void count()
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 4 - (column % 4);
		else
			column++;
	ECHO;
}

/*
int typeCheck()
{
	if (yytext == type_name)
		return (TYPE_NAME);
	return (IDENTIFIER);
}
*/
