#line 2 "Parser/ansicLex.c"

#line 4 "Parser/ansicLex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[280] =
    {   0,
        0,    0,   99,   97,   96,   96,   84,   97,   90,   83,
       97,   78,   79,   88,   87,   75,   86,   82,   89,   40,
       41,   76,   72,   91,   77,   92,   95,   38,   38,   80,
       81,   93,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   73,   94,   74,
       85,   71,    0,   49,    0,   57,   66,   58,    0,    0,
       55,   63,   53,   64,   54,   65,    0,   44,    1,    2,
       56,   45,   40,    0,    0,   40,    0,   41,   41,   62,
       68,   70,   69,   61,   38,    0,    0,   59,   38,   38,
       38,   38,   38,   38,   38,   11,   38,   38,   38,   38,

       38,   38,   38,   19,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   60,   67,   42,   50,
        0,   44,    2,   44,    0,   45,    0,   43,    0,   39,
       52,   51,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   17,   38,   20,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,    0,   44,    0,   44,    0,   45,
       43,   47,   48,   39,   39,    3,    4,   38,    6,    7,
       38,   38,   38,   38,   13,   14,   38,   38,   38,   18,
       21,   38,   38,   38,   38,   38,   38,   38,   38,   36,

       38,   38,   38,   33,   38,   38,    0,   44,   47,   47,
       47,   47,   48,    0,   39,   39,    5,    8,   38,   38,
       38,   38,   37,   16,   38,   38,   24,   38,   38,   38,
       38,   38,   38,   31,   38,   38,   35,    0,   47,   47,
       47,   47,    0,   47,   47,   46,   39,   38,   38,   12,
       15,   38,   23,   25,   26,   27,   28,   29,   38,   38,
       38,   47,    0,   47,   47,   48,   46,   38,   10,   38,
       30,   38,   38,   47,    9,   22,   32,   34,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   29,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   48,   49,
       50,   51,   29,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    6,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[290] =
    {   0,
        0,    0,  516,  517,  517,  517,  492,   60,  491,   59,
      473,  517,  517,  477,   55,  517,   56,   54,   65,   80,
      124,  517,  517,   52,  476,   60,  517,    0,   81,  517,
      517,  470,  435,   35,   56,   27,   43,   66,  439,   60,
      438,  446,   60,   56,  431,  429,  434,  517,   68,  517,
      517,  517,   91,  517,  474,  517,  517,  517,  110,  468,
      517,  517,  517,  517,  517,  517,  460,  131,  517,    0,
      517,  157,   87,  105,  150,  150,  458,    0,  159,  446,
      517,  517,  517,  445,    0,  123,  433,  517,  412,  415,
      423,  407,  422,  408,  412,  398,  399,  396,  390,  396,

      392,  389,  386,    0,  385,  388,   83,  383,   93,  140,
      387,  376,  379,  107,   84,  384,  517,  517,  517,  517,
      198,  517,    0,  201,  218,  517,  176,  221,    0,  226,
      517,  517,  378,  377,  386,  380,  366,   80,  380,  378,
      374,  360,  366,  353,  368,    0,  354,    0,  360,  356,
      342,  344,  346,  353,  339,  337,  333,  344,  341,  331,
      333,  337,  339,  326,  183,  241,  258,  517,  190,  261,
      517,  255,  292,  328,  268,    0,    0,  326,    0,    0,
      317,  312,  298,  305,    0,    0,  296,  300,  284,    0,
        0,  284,  284,  281,  286,  275,  279,  282,  278,    0,

      276,  265,  270,    0,  258,  265,  204,  332,  372,  517,
      260,  408,  517,    0,  314,  136,    0,    0,  256,  257,
      259,  248,    0,    0,  241,  245,    0,  253,  250,  247,
      230,  230,  225,    0,  216,  216,    0,    0,  174,    0,
      444,  517,    0,  199,    0,  197,  333,  200,  200,    0,
        0,  211,    0,    0,    0,    0,    0,    0,  204,  193,
      178,  203,    0,  212,    0,  215,  517,  162,    0,  144,
        0,  151,  141,  217,    0,    0,    0,    0,  517,  491,
      497,  499,  505,  508,  165,  158,  151,  142,  135
    } ;

static const flex_int16_t yy_def[290] =
    {   0,
      279,    1,  279,  279,  279,  279,  279,  280,  279,  279,
      281,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  282,  282,  279,
      279,  279,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  279,  279,  279,
      279,  279,  280,  279,  280,  279,  279,  279,  281,  281,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  283,
      279,  279,   20,  279,  279,  279,  284,   21,  279,  279,
      279,  279,  279,  279,  282,  280,  281,  279,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,

      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  279,  279,  279,  279,
      279,  279,  283,  279,  279,  279,  279,  279,  285,  284,
      279,  279,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  279,  279,  279,  279,  279,  279,
      279,  285,  279,  279,  279,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,

      282,  282,  282,  282,  282,  282,  279,  279,  279,  279,
      173,  279,  279,  286,  174,  174,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  287,  209,  209,
      279,  279,  288,  212,  241,  286,  279,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  287,  289,  241,  241,  288,  279,  282,  282,  282,
      282,  282,  282,  289,  282,  282,  282,  282,    0,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279
    } ;

static const flex_int16_t yy_nxt[582] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   28,   29,
       28,   28,   30,    4,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   28,   40,   28,   41,   28,   28,   28,
       28,   42,   43,   44,   45,   46,   47,   28,   28,   28,
       48,   49,   50,   51,   54,   57,   62,   95,   67,   64,
       68,   68,   68,   80,   81,   69,   96,   63,   65,   66,
       70,   58,   83,   84,   90,   86,   91,   71,   87,   97,
      117,   98,   92,   55,   72,   54,   73,   73,   74,   93,

       99,  104,  100,  108,  109,   94,   75,  112,  105,   76,
       76,   77,  101,  110,  113,  102,  111,  119,  279,   72,
       75,   74,   74,   74,   55,  150,   76,   54,  162,  118,
      163,   75,  181,  182,   76,  153,  151,   77,   72,  274,
       78,   78,   78,   60,  279,   75,  266,   68,   68,   68,
       75,  160,  154,   79,   79,  262,   55,  121,  122,  161,
      122,  127,  246,  127,   75,  247,  128,  128,  128,  172,
       79,  121,  122,  124,  124,  124,  155,  122,   79,   76,
       76,  278,  247,  125,  126,  279,  126,  279,   79,   79,
      277,  156,  128,  128,  128,  276,   76,  125,  126,  166,

      166,  166,  275,  126,   76,   79,  170,  170,  170,  165,
      279,  165,  279,   79,  166,  166,  166,  124,  124,  124,
      208,  208,  208,  279,  273,  279,  267,  167,  168,  169,
      168,  169,  210,  272,  170,  170,  170,  128,  128,  128,
      173,  167,  168,  267,  213,  271,  242,  168,  171,  210,
      171,  270,  174,  269,  268,  175,  175,  166,  166,  166,
      261,  213,  171,  242,  260,  259,  174,  171,  122,  207,
      122,  207,  175,  258,  208,  208,  208,  170,  170,  170,
      175,  209,  122,  257,  210,  256,  241,  122,  126,  242,
      126,  255,  254,  253,  252,  209,  251,  175,  175,  250,

      241,  210,  126,  249,  248,  237,  242,  126,  211,  211,
      211,  236,  235,  234,  175,  233,  232,  211,  212,  211,
      231,  213,  175,  230,  229,  279,  228,  279,  211,  211,
      211,  211,  212,  211,  227,  226,  225,  224,  213,  214,
      223,  214,  173,  247,  215,  215,  215,  222,  208,  208,
      208,  221,  220,  215,  216,  215,  219,  175,  175,  168,
      247,  168,  175,  175,  215,  215,  215,  215,  216,  215,
      218,  217,  206,  168,  175,  205,  204,  203,  168,  175,
      202,  201,  175,  238,  200,  238,  199,  175,  239,  239,
      239,  198,  197,  196,  195,  194,  193,  239,  240,  239,

      192,  210,  191,  190,  189,  188,  187,  186,  239,  239,
      239,  239,  240,  239,  185,  184,  183,  180,  210,  243,
      179,  243,  178,  177,  244,  244,  244,  176,  164,  159,
      158,  157,  152,  244,  245,  244,  149,  242,  148,  147,
      146,  145,  144,  143,  244,  244,  244,  244,  245,  244,
      142,  141,  140,  139,  242,  263,  138,  263,  137,  136,
      264,  264,  264,  135,  134,  133,   60,  132,  131,  264,
      265,  264,  129,  242,  120,   59,   53,  116,  115,  114,
      264,  264,  264,  264,  265,  264,  107,  106,  103,   89,
      242,   53,   88,   53,   53,   53,   53,   59,   82,   61,

       59,   59,   59,   85,   85,  123,   60,  123,  123,  123,
      123,  130,  130,   56,   52,  279,    3,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279
    } ;

static const flex_int16_t yy_chk[582] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   10,   15,   36,   18,   17,
       18,   18,   18,   24,   24,   19,   36,   15,   17,   17,
       19,   10,   26,   26,   34,   29,   34,   19,   29,   37,
       49,   37,   35,    8,   20,   53,   20,   20,   20,   35,

       37,   40,   38,   43,   43,   35,   20,   44,   40,   20,
       20,   20,   38,   43,   44,   38,   43,   59,   73,   74,
       20,   74,   74,   74,   53,  107,   20,   86,  115,   49,
      115,   74,  138,  138,   20,  109,  107,   20,   21,  289,
       21,   21,   21,   59,   73,   74,  288,   68,   68,   68,
       21,  114,  109,   21,   21,  287,   86,   68,   68,  114,
       68,   75,  286,   75,   21,  216,   75,   75,   75,  285,
       21,   68,   68,   72,   72,   72,  110,   68,   21,   76,
       76,  273,  216,   72,   72,  239,   72,  239,   79,   79,
      272,  110,  127,  127,  127,  270,   76,   72,   72,  165,

      165,  165,  268,   72,   76,   79,  169,  169,  169,  121,
      244,  121,  244,   79,  121,  121,  121,  124,  124,  124,
      207,  207,  207,  264,  261,  264,  246,  124,  124,  125,
      124,  125,  262,  260,  125,  125,  125,  128,  128,  128,
      130,  124,  124,  246,  266,  259,  274,  124,  128,  262,
      128,  252,  130,  249,  248,  130,  130,  166,  166,  166,
      236,  266,  128,  274,  235,  233,  130,  128,  166,  167,
      166,  167,  130,  232,  167,  167,  167,  170,  170,  170,
      130,  172,  166,  231,  172,  230,  211,  166,  170,  211,
      170,  229,  228,  226,  225,  172,  222,  175,  175,  221,

      211,  172,  170,  220,  219,  206,  211,  170,  173,  173,
      173,  205,  203,  202,  175,  201,  199,  173,  173,  173,
      198,  173,  175,  197,  196,  215,  195,  215,  173,  173,
      173,  173,  173,  173,  194,  193,  192,  189,  173,  174,
      188,  174,  174,  215,  174,  174,  174,  187,  208,  208,
      208,  184,  183,  174,  174,  174,  182,  174,  174,  208,
      215,  208,  247,  247,  174,  174,  174,  174,  174,  174,
      181,  178,  164,  208,  174,  163,  162,  161,  208,  247,
      160,  159,  174,  209,  158,  209,  157,  247,  209,  209,
      209,  156,  155,  154,  153,  152,  151,  209,  209,  209,

      150,  209,  149,  147,  145,  144,  143,  142,  209,  209,
      209,  209,  209,  209,  141,  140,  139,  137,  209,  212,
      136,  212,  135,  134,  212,  212,  212,  133,  116,  113,
      112,  111,  108,  212,  212,  212,  106,  212,  105,  103,
      102,  101,  100,   99,  212,  212,  212,  212,  212,  212,
       98,   97,   96,   95,  212,  241,   94,  241,   93,   92,
      241,  241,  241,   91,   90,   89,   87,   84,   80,  241,
      241,  241,   77,  241,   67,   60,   55,   47,   46,   45,
      241,  241,  241,  241,  241,  241,   42,   41,   39,   33,
      241,  280,   32,  280,  280,  280,  280,  281,   25,   14,

      281,  281,  281,  282,  282,  283,   11,  283,  283,  283,
      283,  284,  284,    9,    7,    3,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[99] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Parser/ansicLex.l"
#line 2 "Parser/ansicLex.l"
#include "../Tree/tree.h"
#include "ansicParser.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void count();
void comment();
// int typeCheck();

int column = 0;
#line 703 "Parser/ansicLex.c"
#line 704 "Parser/ansicLex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 25 "Parser/ansicLex.l"


#line 924 "Parser/ansicLex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 280 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 517 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "Parser/ansicLex.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "Parser/ansicLex.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_AUTO,yylineno);			return(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_BOOL,yylineno); 		return(BOOL);	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_BREAK,yylineno);		return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CASE,yylineno);			return(CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CHAR,yylineno);			return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONST,yylineno);		return(CONST); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONTINUE,yylineno);		return(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_DEFAULT,yylineno);		return(DEFAULT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_DO,yylineno);			return(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_DOUBLE,yylineno);		return(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ELSE,yylineno);			return(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ENUM,yylineno);			return(ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_EXTERN,yylineno);		return(EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_FLOAT,yylineno);		return(FLOAT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_FOR,yylineno);			return(FOR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_GOTO,yylineno);			return(GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_IF,yylineno);			return(IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_INT,yylineno);			return(INT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_LONG,yylineno);			return(LONG); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_REGISTER,yylineno);		return(REGISTER); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_RETURN,yylineno);		return(RETURN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_LONG,yylineno);      	return(SHORT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_SIGNED,yylineno);		return(SIGNED); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_SIZEOF,yylineno);		return(SIZEOF); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_STATIC,yylineno);		return(STATIC); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_STRUCT,yylineno);		return(STRUCT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_SWITCH,yylineno);		return(SWITCH); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_TYPEDEF,yylineno);		return(TYPEDEF); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_UNION,yylineno);		return(UNION); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_UNSIGNED,yylineno);		return(UNSIGNED); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_VOID,yylineno);			return(VOID); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_VOLATILE,yylineno);		return(VOLATILE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_WHILE,yylineno);		return(WHILE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_TRUE,yylineno);			return(TRUE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_FALSE,yylineno);		return(FALSE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_IDENTIFIER,yylineno);	return(IDENTIFIER); /*IDENTIFIER*/ }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 68 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_INT,yylineno);	return(CONSTANT_INT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 69 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_INT,yylineno);	return(CONSTANT_INT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 70 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_INT,yylineno);	return(CONSTANT_INT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 71 "Parser/ansicLex.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 73 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_DOUBLE,yylineno);	return(CONSTANT_DOUBLE); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 74 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_DOUBLE,yylineno);	return(CONSTANT_DOUBLE); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 75 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_CONSTANT_DOUBLE,yylineno);	return(CONSTANT_DOUBLE); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 76 "Parser/ansicLex.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 77 "Parser/ansicLex.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 78 "Parser/ansicLex.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 79 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_STRING_LITERAL,yylineno);	return(STRING_LITERAL); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 81 "Parser/ansicLex.l"
{ count(); return(ELLIPSIS); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 82 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_RIGHT_,yylineno);	return(RIGHT_ASSIGN); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_LEFT,yylineno);		return(LEFT_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 84 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_ADD,yylineno);		return(ADD_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 85 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_SUB,yylineno);		return(SUB_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 86 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_MUL,yylineno);		return(MUL_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_DIV,yylineno);		return(DIV_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 88 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_MOD,yylineno);		return(MOD_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 89 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_AND,yylineno);		return(AND_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 90 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_XOR,yylineno);		return(XOR_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 91 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_ASSIGN_OR,yylineno);		return(OR_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 92 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_RIGHT,yylineno);			return(RIGHT_OP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 93 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_LEFT,yylineno);			return(LEFT_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 94 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_INC,yylineno);			return(INC_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 95 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_DEC,yylineno);			return(DEC_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 96 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_PTR,yylineno);			return(PTR_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 97 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_AND,yylineno);			return(AND_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_OR,yylineno);			return(OR_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 99 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_LE,yylineno);			return(LE_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 100 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_GE,yylineno);			return(GE_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 101 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_EQ,yylineno);			return(EQ_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 102 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(L_OP_NE,yylineno);			return(NE_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 103 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(';',yylineno);return(';'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 104 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('{',yylineno);return('{'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 105 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('}',yylineno);return('}'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 106 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(',',yylineno);return(','); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 107 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(':',yylineno);return(':'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 108 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('=',yylineno);return('='); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 109 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('(',yylineno);return('('); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 110 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(')',yylineno);return(')'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 111 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('[',yylineno);return('['); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 112 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf(']',yylineno);return(']'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 113 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('.',yylineno);return('.'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 114 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('&',yylineno);return('&'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 115 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('!',yylineno);return('!'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 116 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('~',yylineno);return('~'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 117 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('-',yylineno);return('-'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 118 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('+',yylineno);return('+'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 119 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('*',yylineno);return('*'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 120 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('/',yylineno);return('/'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 121 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('%',yylineno);return('%'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 122 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('<',yylineno);return('<'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 123 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('>',yylineno);return('>'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 124 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('^',yylineno);return('^'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 125 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('|',yylineno);return('|'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 126 "Parser/ansicLex.l"
{ count(); yylval.gt = createLeaf('?',yylineno);return('?'); }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 128 "Parser/ansicLex.l"
{ count(); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 129 "Parser/ansicLex.l"
{ }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 131 "Parser/ansicLex.l"
ECHO;
	YY_BREAK
#line 1483 "Parser/ansicLex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 280 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 280 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 279);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 131 "Parser/ansicLex.l"


int yywrap()
{
    return 1;
}

void comment() 
{ 
    char c, c1; 
    printf("/*");
    while(1)
    {
        while ((c = input()) != '*' && c != 0) 
            putchar(c); 
        if ((c1 = input()) != '/' && c != 0) 
            unput(c1);
        else
            break;
    }
    if (c != 0) 
    {
        putchar(c);
        putchar(c1);
    }
}

void count()
{
    int i;

    for (i = 0; yytext[i] != '\0'; i++)
        if (yytext[i] == '\n')
            column = 0;
        else if (yytext[i] == '\t')
            column += 4 - (column % 4);
        else
            column++;
    ECHO;
}

/*
int typeCheck()
{
    if (yytext == type_name)
        return (TYPE_NAME);
    return (IDENTIFIER);
}
*/

